---
title: "OECD Countries By Inequality Index"
author: "Bruce Johnston"
date: "July 1, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
##<span style="color:red"> Distribution of Inequality in OECD Countries By Continent Using Gini Coefficient </span> ##
#<span style = "color:green"> 0 = Completely Equal; 1 = Completely Unequal </span>#

```{r, echo=FALSE}
library(leaflet);
library(plotly);
set.seed(1321);

Country_Names <- c("Iceland", "Norway", "Denmark", "Slovenia", "Finland",
 "Czech Republic", "Belgium", "Slovak Republic", "Austria", "Sweden", "Luxembourg","Netherlands",
 "Hungary", "Germany", "France", "Switzerland", "Poland", "Korea", "Ireland", "Canada", "Italy", "Japan",
 "New Zealand", "Australia", "Portugal", "Greece", "Spain", "Latvia", "United Kingdom", "Estonia", 
"Israel", "Turkey", "United States", "Mexico", "Chile");

Continents <- c("Americas", "Europe", "Europe", "Europe", "Europe", "Europe", "Europe", "Europe", "Europe", "Europe", "Europe", "Europe","Europe","Europe","Europe","Europe","Europe", "Asia", "Europe", "Americas", "Europe", "Asia", "Asia", "Asia", "Europe", "Europe", "Europe", "Europe", "Europe", "Europe", "MidEast", "MidEast", "Americas", "Americas", "Americas");

Country_Coefficients <- c(0.244,0.252,0.254,0.255,0.257,0.262,0.268,
0.269,0.280,0.281,0.281,0.283,0.288,0.292,0.294, 0.295,0.300,0.302,0.309,
0.322,0.325,0.330,0.333,0.337,0.342,0.343,0.346,0.352,0.358,0.361,0.365,
0.393,0.394,0.459,0.465);

Lats <- c(64.10, 59.55, 55.41, 46.04, 60.15, 50.05, 50.51, 48.10, 48.12, 59.20, 49.37,
52.23, 47.29,52.30,48.50, 46.57, 52.13, 37.31, 53.21, 45.27, 41.54, 35.69, -41.19, -35.15,
38.42, 37.58, 40.25, 56.53, 51.36, 59.44, 31.77, 39.57, 39.91, 19.20, -33.24);

Longs <- c(-21.57, 10.45, 12.34, 14.33, 25.03, 14.22, 4.21, 17.07, 16.22, 18.03,
6.09, 04.54, 19.05, 13.25, 2.20, 7.28, 21.00, 126.58, -6.15, -75.42, 12.29,
139.69, 174.46, 149.08, -9.10, 23.46, -3.45, 24.08, -0.05, 24.75, 35.21, 32.54,
-77.02, -99.10, -70.40);

df <- data.frame(lat = Lats, lng = Longs);
df2 <- data.frame(Country = Country_Names, Gini = Country_Coefficients);
df3 <- data.frame(Continent = Continents, Gini = Country_Coefficients)

p <- plot_ly(data = df3, x = ~Gini, color = ~Continent, type = 'box')

p
  
```

